# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\USER\Desktop\Benny\benny\PyQt5\UI\天气查询\page_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_page_1(object):
    def setupUi(self, page_1):
        page_1.setObjectName("page_1")
        page_1.setWindowModality(QtCore.Qt.WindowModal)
        page_1.resize(313, 320)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("f:\\USER\\Desktop\\Benny\\benny\\PyQt5\\UI\\天气查询\\../../ICO/test.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        page_1.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(page_1)
        self.label.setGeometry(QtCore.QRect(60, 70, 31, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(page_1)
        self.label_2.setGeometry(QtCore.QRect(60, 120, 41, 16))
        self.label_2.setScaledContents(False)
        self.label_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_2.setObjectName("label_2")
        self.zhanghao = QtWidgets.QLineEdit(page_1)
        self.zhanghao.setGeometry(QtCore.QRect(120, 70, 113, 21))
        self.zhanghao.setCursorPosition(0)
        self.zhanghao.setObjectName("zhanghao")
        self.mima = QtWidgets.QLineEdit(page_1)
        self.mima.setGeometry(QtCore.QRect(120, 120, 113, 21))
        self.mima.setEchoMode(QtWidgets.QLineEdit.Password)
        self.mima.setCursorPosition(0)
        self.mima.setReadOnly(False)
        self.mima.setPlaceholderText("")
        self.mima.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.mima.setObjectName("mima")
        self.pushButton = QtWidgets.QPushButton(page_1)
        self.pushButton.setGeometry(QtCore.QRect(110, 230, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(page_1)
        self.label.linkActivated['QString'].connect(self.zhanghao.redo)
        self.label_2.linkActivated['QString'].connect(self.mima.redo)
        QtCore.QMetaObject.connectSlotsByName(page_1)
        page_1.setTabOrder(self.zhanghao, self.mima)
        page_1.setTabOrder(self.mima, self.pushButton)

    def retranslateUi(self, page_1):
        _translate = QtCore.QCoreApplication.translate
        page_1.setWindowTitle(_translate("page_1", "密码登录"))
        self.label.setText(_translate("page_1", "账号"))
        self.label_2.setText(_translate("page_1", "密码"))
        self.pushButton.setText(_translate("page_1", "登录"))
